4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

empty_arr=np.zeros((2,2))
arr1=np.ones((4,2))
arr2=np.full((4,2),1)
arr3=np.zeros_like(arr1)
arr4=np.ones_like((arr1))
new_list=[1,2,3,4]
new_arr=np.array((new_list))
print("empty array=\n",empty_arr,"\nall ones array=\n", arr1,"\n full array\n=", arr2,"\nzero array=\n", arr3,"\nall one array=\n", arr4,"\nlist into array=\n", new_arr)



empty array=
 [[0. 0.]
 [0. 0.]] 
all ones array=
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
 full array
= [[1 1]
 [1 1]
 [1 1]
 [1 1]] 
zero array=
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]] 
all one array=
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]] 
list into array=
 [1 2 3 4]


4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Num

4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

q1_arr=np.arange(10,50)
print("array with values ranging from 10 to 49=",q1_arr)
q2_arr=np.arange(0,9).reshape(3,3)
print("3x3 matrix from 0 to 8=\n",q2_arr)
q3_arr=np.eye(3)
print("3x3 identity matrix=\n",q3_arr)
q4_arr=np.random.random(30)
print("mean of random array=",q4_arr.mean())
q5_arr=np.random.random((10,10))
print("minimum value=",q5_arr.min(),"maximum value=",q5_arr.max())
Q6_arr=np.zeros(10)
Q6_arr[4]=1
print("zero array with 5th element as 1=",Q6_arr)
q7_arr=np.array([1,2,0,0,4,0])
print("reverse array=",q7_arr[::-1])
q8_arr=np.ones((5,5))
q8_arr[1:-1,1:-1]=0
print("2d array with 1 on border and 0 inside=\n",q8_arr)
q9_arr=np.zeros((8,8),dtype=int)
q9_arr[1::2,::2]=1
q9_arr[::2,1::2]=1
print("8x8 checkerboard pattern=\n",q9_arr)
#<change dimension of array and experiment in follwing>


array with values ranging from 10 to 49= [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
3x3 matrix from 0 to 8=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3x3 identity matrix=
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
mean of random array= 0.44435418264972276
minimum value= 0.04601150429574263 maximum value= 0.9966077858772477
zero array with 5th element as 1= [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
reverse array= [0 4 0 0 2 1]
2d array with 1 on border and 0 inside=
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
8x8 checkerboard pattern=
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
x=np.array([[1,2],[3,5]])
y=np.array([[5,6],[7,8]])
v=np.array([[9,10]])
w=np.array([[11,12]])
add_arr=x+y
print("add 2 arrays:",add_arr)
sub_arr=x-y
print("subtract 2 arrays:",sub_arr)
mult_arr=2*x
print("multiply any array with an integer of your choice:",mult_arr)
sq_arr=x**2
print("square of each element of any array:", sq_arr)
v=v.flatten()
w=w.flatten()
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("v.w:",dot_vw)
print("x.v:",dot_xv)
print("x.y:",dot_xy)
concat_xy_row = np.concatenate((x, y), axis=0)
concat_vw_col = np.concatenate((v.reshape(-1, 1), w.reshape(-1, 1)), axis=1)
print("Concatenate along rows (x and y):\n", concat_xy_row)
print("Concatenate along columns (v and w):\n", concat_vw_col)
try:
    concat_xv = np.concatenate((x, v), axis=0)
except ValueError as e:
    concat_xv_error = str(e)
print("Error in concatenating x and v:", concat_xv_error)

add 2 arrays: [[ 6  8]
 [10 13]]
subtract 2 arrays: [[-4 -4]
 [-4 -3]]
multiply any array with an integer of your choice: [[ 2  4]
 [ 6 10]]
square of each element of any array: [[ 1  4]
 [ 9 25]]
v.w: 219
x.v: [29 77]
x.y: [[19 22]
 [50 58]]
Concatenate along rows (x and y):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate along columns (v and w):
 [[ 9 11]
 [10 12]]
Error in concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
#1
import numpy as np

# Define matrices A and B
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A * A^-1 = I
A_inv = np.linalg.inv(A)  # Calculate the inverse of A
identity_matrix = np.dot(A, A_inv)  # Multiply A with its inverse

# Check if the result is approximately an identity matrix
is_identity = np.allclose(identity_matrix, np.eye(A.shape[0]))

# 2. Prove AB != BA
AB = np.dot(A, B)  # Compute A * B
BA = np.dot(B, A)  # Compute B * A
are_not_equal = not np.array_equal(AB, BA)  # Compare the two results

# 3. Prove (AB)^T = B^T * A^T
AB_T = np.transpose(AB)  # Compute the transpose of AB
BT_AT = np.dot(np.transpose(B), np.transpose(A))  # Compute B^T * A^T
is_transpose_equal = np.allclose(AB_T, BT_AT)

# Print results
print("1. A * A^-1 = I:")
print(identity_matrix)
print("Is A * A^-1 approximately the identity matrix?", is_identity)

print("\n2. AB != BA:")
print("AB:\n", AB)
print("BA:\n", BA)
print("Are AB and BA unequal?", are_not_equal)

print("\n3. (AB)^T = B^T * A^T:")
print("(AB)^T:\n", AB_T)
print("B^T * A^T:\n", BT_AT)
print("Is (AB)^T equal to B^T * A^T?", is_transpose_equal)


#2

# Define the coefficient matrix A and the constant vector B
A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])
B = np.array([-1, -3, 9])

# Compute the inverse of A
A_inv = np.linalg.inv(A)

# Solve for X using the inverse method
X = np.dot(A_inv, B)

# Verify the solution by calculating A * X
verification = np.dot(A, X)

# Display results
print("Matrix A:\n", A)
print("Vector B:\n", B)
print("\nSolution Vector X (x, y, z):\n", X)
print("\nVerification (A * X):\n", verification)
print("Does A * X approximately equal B?", np.allclose(verification, B))


1. A * A^-1 = I:
[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is A * A^-1 approximately the identity matrix? True

2. AB != BA:
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
Are AB and BA unequal? True

3. (AB)^T = B^T * A^T:
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Is (AB)^T equal to B^T * A^T? True
Matrix A:
 [[ 2 -3  1]
 [ 1 -1  2]
 [ 3  1 -1]]
Vector B:
 [-1 -3  9]

Solution Vector X (x, y, z):
 [ 2.  1. -2.]

Verification (A * X):
 [-1. -3.  9.]
Does A * X approximately equal B? True


4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.
4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

# size of list
list_size = 1_000_000
matrix_size = 1000

# Create lists and arrays
list1 = [i for i in range(list_size)]
list2 = [i for i in range(list_size)]

array1 = np.array(list1)
array2 = np.array(list2)

# 1. Element-wise Addition
# using Python lists
start_time = time.time()
result_list_add = [list1[i] + list2[i] for i in range(list_size)]
list_add_time = time.time() - start_time

# using NumPy arrays
start_time = time.time()
result_array_add = array1 + array2
array_add_time = time.time() - start_time

print(f"Element-wise Addition: Python Lists = {list_add_time:.6f}s, NumPy Arrays = {array_add_time:.6f}s")

# 2. Element-wise Multiplication
# using Python lists
start_time = time.time()
result_list_mul = [list1[i] * list2[i] for i in range(list_size)]
list_mul_time = time.time() - start_time

# using NumPy arrays
start_time = time.time()
result_array_mul = array1 * array2
array_mul_time = time.time() - start_time

print(f"Element-wise Multiplication: Python Lists = {list_mul_time:.6f}s, NumPy Arrays = {array_mul_time:.6f}s")

# 3. Dot Product
# using Python lists
start_time = time.time()
result_list_dot = sum(list1[i] * list2[i] for i in range(list_size))
list_dot_time = time.time() - start_time

# using NumPy arrays
start_time = time.time()
result_array_dot = np.dot(array1, array2)
array_dot_time = time.time() - start_time

print(f"Dot Product: Python Lists = {list_dot_time:.6f}s, NumPy Arrays = {array_dot_time:.6f}s")

# 4. Matrix Multiplication
# Create matrices
matrix1 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]
matrix2 = [[i for i in range(matrix_size)] for _ in range(matrix_size)]

np_matrix1 = np.array(matrix1)
np_matrix2 = np.array(matrix2)

# Python lists
start_time = time.time()
result_matrix = [[sum(a * b for a, b in zip(matrix1_row, matrix2_col)) for matrix2_col in zip(*matrix2)] for matrix1_row in matrix1]
matrix_mul_time = time.time() - start_time

# NumPy arrays
start_time = time.time()
result_np_matrix = np.dot(np_matrix1, np_matrix2)
np_matrix_mul_time = time.time() - start_time

print(f"Matrix Multiplication: Python Lists = {matrix_mul_time:.6f}s, NumPy Arrays = {np_matrix_mul_time:.6f}s")


Element-wise Addition: Python Lists = 0.172396s, NumPy Arrays = 0.005909s
Element-wise Multiplication: Python Lists = 0.193966s, NumPy Arrays = 0.005148s
Dot Product: Python Lists = 0.258770s, NumPy Arrays = 0.002180s
Matrix Multiplication: Python Lists = 207.190578s, NumPy Arrays = 1.401619s
